// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// h_Emax_IV_i_ind
double h_Emax_IV_i_ind(const double t, const NumericVector s, const NumericVector d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_h_Emax_IV_i_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(h_Emax_IV_i_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// h_5PL_IV_i_ind
double h_5PL_IV_i_ind(const double t, const NumericVector s, const NumericVector d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_h_5PL_IV_i_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(h_5PL_IV_i_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// h_Emax_IV_ind
NumericVector h_Emax_IV_ind(const NumericVector t, const NumericMatrix s, const NumericMatrix d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_h_Emax_IV_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(h_Emax_IV_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// h_5PL_IV_ind
NumericVector h_5PL_IV_ind(const NumericVector t, const NumericMatrix s, const NumericMatrix d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_h_5PL_IV_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(h_5PL_IV_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// H_Emax_IV_onepiece_ind
double H_Emax_IV_onepiece_ind(const double t, const NumericVector s, const NumericVector d, const int doseNum, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_H_Emax_IV_onepiece_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP doseNumSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int >::type doseNum(doseNumSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(H_Emax_IV_onepiece_ind(t, s, d, doseNum, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// H_Emax_IV_i_ind
double H_Emax_IV_i_ind(const double t, const NumericVector s, const NumericVector d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_H_Emax_IV_i_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(H_Emax_IV_i_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// H_Emax_IV_ind
NumericVector H_Emax_IV_ind(const NumericVector t, const NumericMatrix s, const NumericMatrix d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_H_Emax_IV_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(H_Emax_IV_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// S_Emax_IV_ind
NumericVector S_Emax_IV_ind(const NumericVector t, const NumericMatrix s, const NumericMatrix d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_S_Emax_IV_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(S_Emax_IV_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// F_Emax_IV_ind
NumericVector F_Emax_IV_ind(const NumericVector t, const NumericMatrix s, const NumericMatrix d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_F_Emax_IV_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(F_Emax_IV_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// f_Emax_IV_ind
NumericVector f_Emax_IV_ind(const NumericVector t, const NumericMatrix s, const NumericMatrix d, const NumericVector parmPK, const NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_f_Emax_IV_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(f_Emax_IV_ind(t, s, d, parmPK, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// Gibbs_Emax_IV_MTD
List Gibbs_Emax_IV_MTD(List data, const NumericVector initPK, const NumericVector initPD, const NumericVector initSD, const int samplesize, const NumericVector limit, const NumericVector tuning, const NumericVector lowerbound, const int SliceSampleSize);
RcppExport SEXP _MTDSemiPKPD_Gibbs_Emax_IV_MTD(SEXP dataSEXP, SEXP initPKSEXP, SEXP initPDSEXP, SEXP initSDSEXP, SEXP samplesizeSEXP, SEXP limitSEXP, SEXP tuningSEXP, SEXP lowerboundSEXP, SEXP SliceSampleSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type initPK(initPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type initPD(initPDSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type initSD(initSDSEXP);
    Rcpp::traits::input_parameter< const int >::type samplesize(samplesizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tuning(tuningSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type lowerbound(lowerboundSEXP);
    Rcpp::traits::input_parameter< const int >::type SliceSampleSize(SliceSampleSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(Gibbs_Emax_IV_MTD(data, initPK, initPD, initSD, samplesize, limit, tuning, lowerbound, SliceSampleSize));
    return rcpp_result_gen;
END_RCPP
}
// Gibbs_Emax_IV_MTD_IIV
List Gibbs_Emax_IV_MTD_IIV(List data, const NumericMatrix initPK, const NumericVector initPD, const NumericVector initSD, const NumericVector initIIV, const int samplesize, const NumericVector limit, const NumericVector tuning, const NumericVector lowerbound, const int SliceSampleSize);
RcppExport SEXP _MTDSemiPKPD_Gibbs_Emax_IV_MTD_IIV(SEXP dataSEXP, SEXP initPKSEXP, SEXP initPDSEXP, SEXP initSDSEXP, SEXP initIIVSEXP, SEXP samplesizeSEXP, SEXP limitSEXP, SEXP tuningSEXP, SEXP lowerboundSEXP, SEXP SliceSampleSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type initPK(initPKSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type initPD(initPDSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type initSD(initSDSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type initIIV(initIIVSEXP);
    Rcpp::traits::input_parameter< const int >::type samplesize(samplesizeSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type tuning(tuningSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type lowerbound(lowerboundSEXP);
    Rcpp::traits::input_parameter< const int >::type SliceSampleSize(SliceSampleSizeSEXP);
    rcpp_result_gen = Rcpp::wrap(Gibbs_Emax_IV_MTD_IIV(data, initPK, initPD, initSD, initIIV, samplesize, limit, tuning, lowerbound, SliceSampleSize));
    return rcpp_result_gen;
END_RCPP
}
// CtEV_i_ind
double CtEV_i_ind(const double t, const NumericVector s, const NumericVector d, const NumericVector parmPK);
RcppExport SEXP _MTDSemiPKPD_CtEV_i_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    rcpp_result_gen = Rcpp::wrap(CtEV_i_ind(t, s, d, parmPK));
    return rcpp_result_gen;
END_RCPP
}
// CtIV_i_ind
double CtIV_i_ind(const double t, const NumericVector s, const NumericVector d, const NumericVector parmPK);
RcppExport SEXP _MTDSemiPKPD_CtIV_i_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    rcpp_result_gen = Rcpp::wrap(CtIV_i_ind(t, s, d, parmPK));
    return rcpp_result_gen;
END_RCPP
}
// Emax_ind
double Emax_ind(double c, NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_Emax_ind(SEXP cSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(Emax_ind(c, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// PL5_ind
double PL5_ind(double c, NumericVector parmPD);
RcppExport SEXP _MTDSemiPKPD_PL5_ind(SEXP cSEXP, SEXP parmPDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parmPD(parmPDSEXP);
    rcpp_result_gen = Rcpp::wrap(PL5_ind(c, parmPD));
    return rcpp_result_gen;
END_RCPP
}
// AUCIV_i_ind
double AUCIV_i_ind(const double t, const NumericVector s, const NumericVector d, const NumericVector parmPK);
RcppExport SEXP _MTDSemiPKPD_AUCIV_i_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPKSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type parmPK(parmPKSEXP);
    rcpp_result_gen = Rcpp::wrap(AUCIV_i_ind(t, s, d, parmPK));
    return rcpp_result_gen;
END_RCPP
}
// S_Emax_IV_postmean_ind
double S_Emax_IV_postmean_ind(const double t, const NumericVector s, const NumericVector d, const NumericMatrix parmPDSample, const NumericMatrix parmPKSample);
RcppExport SEXP _MTDSemiPKPD_S_Emax_IV_postmean_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPDSampleSEXP, SEXP parmPKSampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type parmPDSample(parmPDSampleSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type parmPKSample(parmPKSampleSEXP);
    rcpp_result_gen = Rcpp::wrap(S_Emax_IV_postmean_ind(t, s, d, parmPDSample, parmPKSample));
    return rcpp_result_gen;
END_RCPP
}
// S_Emax_IV_postDis_ind
NumericVector S_Emax_IV_postDis_ind(const double t, const NumericVector s, const NumericVector d, const NumericMatrix parmPDSample, const NumericMatrix parmPKSample);
RcppExport SEXP _MTDSemiPKPD_S_Emax_IV_postDis_ind(SEXP tSEXP, SEXP sSEXP, SEXP dSEXP, SEXP parmPDSampleSEXP, SEXP parmPKSampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type t(tSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type parmPDSample(parmPDSampleSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type parmPKSample(parmPKSampleSEXP);
    rcpp_result_gen = Rcpp::wrap(S_Emax_IV_postDis_ind(t, s, d, parmPDSample, parmPKSample));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MTDSemiPKPD_h_Emax_IV_i_ind", (DL_FUNC) &_MTDSemiPKPD_h_Emax_IV_i_ind, 5},
    {"_MTDSemiPKPD_h_5PL_IV_i_ind", (DL_FUNC) &_MTDSemiPKPD_h_5PL_IV_i_ind, 5},
    {"_MTDSemiPKPD_h_Emax_IV_ind", (DL_FUNC) &_MTDSemiPKPD_h_Emax_IV_ind, 5},
    {"_MTDSemiPKPD_h_5PL_IV_ind", (DL_FUNC) &_MTDSemiPKPD_h_5PL_IV_ind, 5},
    {"_MTDSemiPKPD_H_Emax_IV_onepiece_ind", (DL_FUNC) &_MTDSemiPKPD_H_Emax_IV_onepiece_ind, 6},
    {"_MTDSemiPKPD_H_Emax_IV_i_ind", (DL_FUNC) &_MTDSemiPKPD_H_Emax_IV_i_ind, 5},
    {"_MTDSemiPKPD_H_Emax_IV_ind", (DL_FUNC) &_MTDSemiPKPD_H_Emax_IV_ind, 5},
    {"_MTDSemiPKPD_S_Emax_IV_ind", (DL_FUNC) &_MTDSemiPKPD_S_Emax_IV_ind, 5},
    {"_MTDSemiPKPD_F_Emax_IV_ind", (DL_FUNC) &_MTDSemiPKPD_F_Emax_IV_ind, 5},
    {"_MTDSemiPKPD_f_Emax_IV_ind", (DL_FUNC) &_MTDSemiPKPD_f_Emax_IV_ind, 5},
    {"_MTDSemiPKPD_Gibbs_Emax_IV_MTD", (DL_FUNC) &_MTDSemiPKPD_Gibbs_Emax_IV_MTD, 9},
    {"_MTDSemiPKPD_Gibbs_Emax_IV_MTD_IIV", (DL_FUNC) &_MTDSemiPKPD_Gibbs_Emax_IV_MTD_IIV, 10},
    {"_MTDSemiPKPD_CtEV_i_ind", (DL_FUNC) &_MTDSemiPKPD_CtEV_i_ind, 4},
    {"_MTDSemiPKPD_CtIV_i_ind", (DL_FUNC) &_MTDSemiPKPD_CtIV_i_ind, 4},
    {"_MTDSemiPKPD_Emax_ind", (DL_FUNC) &_MTDSemiPKPD_Emax_ind, 2},
    {"_MTDSemiPKPD_PL5_ind", (DL_FUNC) &_MTDSemiPKPD_PL5_ind, 2},
    {"_MTDSemiPKPD_AUCIV_i_ind", (DL_FUNC) &_MTDSemiPKPD_AUCIV_i_ind, 4},
    {"_MTDSemiPKPD_S_Emax_IV_postmean_ind", (DL_FUNC) &_MTDSemiPKPD_S_Emax_IV_postmean_ind, 5},
    {"_MTDSemiPKPD_S_Emax_IV_postDis_ind", (DL_FUNC) &_MTDSemiPKPD_S_Emax_IV_postDis_ind, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MTDSemiPKPD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
