# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

h_Emax_IV_i_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_h_Emax_IV_i_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

h_5PL_IV_i_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_h_5PL_IV_i_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

h_Emax_IV_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_h_Emax_IV_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

h_5PL_IV_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_h_5PL_IV_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

H_Emax_IV_onepiece_ind <- function(t, s, d, doseNum, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_H_Emax_IV_onepiece_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, doseNum, parmPK, parmPD)
}

H_Emax_IV_i_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_H_Emax_IV_i_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

H_Emax_IV_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_H_Emax_IV_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

S_Emax_IV_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_S_Emax_IV_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

F_Emax_IV_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_F_Emax_IV_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}

f_Emax_IV_ind <- function(t, s, d, parmPK, parmPD) {
    .Call('_MTDSemiPKPD_f_Emax_IV_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK, parmPD)
}






Gibbs_Emax_IV_MTD <- function(data, initPK, initPD, initSD, samplesize, limit, tuning, lowerbound, SliceSampleSize) {
    .Call('_MTDSemiPKPD_Gibbs_Emax_IV_MTD', PACKAGE = 'MTDSemiPKPD', data, initPK, initPD, initSD, samplesize, limit, tuning, lowerbound, SliceSampleSize)
}

Gibbs_Emax_IV_MTD_IIV <- function(data, initPK, initPD, initSD, initIIV, samplesize, limit, tuning, lowerbound, SliceSampleSize) {
    .Call('_MTDSemiPKPD_Gibbs_Emax_IV_MTD_IIV', PACKAGE = 'MTDSemiPKPD', data, initPK, initPD, initSD, initIIV, samplesize, limit, tuning, lowerbound, SliceSampleSize)
}

CtEV_i_ind <- function(t, s, d, parmPK) {
    .Call('_MTDSemiPKPD_CtEV_i_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK)
}

CtIV_i_ind <- function(t, s, d, parmPK) {
    .Call('_MTDSemiPKPD_CtIV_i_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK)
}

Emax_ind <- function(c, parmPD) {
    .Call('_MTDSemiPKPD_Emax_ind', PACKAGE = 'MTDSemiPKPD', c, parmPD)
}

PL5_ind <- function(c, parmPD) {
    .Call('_MTDSemiPKPD_PL5_ind', PACKAGE = 'MTDSemiPKPD', c, parmPD)
}

AUCIV_i_ind <- function(t, s, d, parmPK) {
    .Call('_MTDSemiPKPD_AUCIV_i_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPK)
}

S_Emax_IV_postmean_ind <- function(t, s, d, parmPDSample, parmPKSample) {
    .Call('_MTDSemiPKPD_S_Emax_IV_postmean_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPDSample, parmPKSample)
}

S_Emax_IV_postDis_ind <- function(t, s, d, parmPDSample, parmPKSample) {
    .Call('_MTDSemiPKPD_S_Emax_IV_postDis_ind', PACKAGE = 'MTDSemiPKPD', t, s, d, parmPDSample, parmPKSample)
}

